<div id="validate_secret_modal">
    <div class="message"> Validate Credentials
        <button id="validate_secret_btn" class="primary" onclick="return false;">Check</button>
        <div id="validation_status"></div>
    </div>

    <script type="text/javascript">
        require(['jquery','mage/storage',], function ($) {

            var secret = $("#<?php echo $block->getSecretId() ?>");

            $(document).ready(function(){
                if(secret.val()!="") {
                    $("#validate_secret_btn").prop('disabled', true);
                    return false;
                }
            });

            $('#payment_other_simplcheckout_mode').on('change', function (e) {
                if ($(this).val() === "live") {
                    secret = $("#payment_other_simplcheckout_live_secret");
                } else {
                    secret = $("#payment_other_simplcheckout_test_secret");
                }
            });

            secret.on('keypress','',function(){
                $("#validate_secret_btn").prop('disabled', false);
                return true;
            });

            jQuery(document).on('click', '#validate_secret_modal', function (event) {
                var client_secret = secret.val();
                var client_id = $('#payment_other_simplcheckout_client_id').val();
                $.ajax({
                    showLoader: true,
                    url: "<?php echo $block->getValidateUrl() ?>",
                    type: "POST",
                    data: {client_secret:client_secret, client_id:client_id},
                    success: function(response){
                        if (response.status) {
                            $("#validate_secret_btn").prop('disabled', true);
                        } else {
                            $('#payment_other_simplcheckout_client_id').val('');
                            secret.val('');
                        }

                        $('#validation_status').html(response.message).show();
                        return true;
                    }
                });
            });
        });
    </script>
</div>

