<div id="messages">
    <div class="message"> Validate Credentials
        <button id="validate_secret_btn" class="primary" onclick="return false;">Check</button>
        <div id="valid"></div>
    </div>

    <script type="text/javascript">
        require(['jquery','mage/storage',], function ($) {
            $(document).ready(function(){
                if($("#payment_other_simplcheckout_test_secret").val()!="")
                {
                    $("#validate_secret_btn").prop('disabled', true);
                    return false;
                }
            });

            $('#payment_other_simplcheckout_test_secret').on('keypress','',function(){
                $("#validate_secret_btn").prop('disabled', false);
                return true;
            });

            jQuery(document).on('click', '#messages', function (event)
            {
                param = $("#payment_other_simplcheckout_test_secret").val();
                $.ajax({
                    showLoader: true,
                    url: "<?php echo $block->getValidateUrl() ?>",
                    type: "POST",
                    data: {clientsecret:param},
                    success: function(response){
                        if (response.status)
                            $("#validate_secret_btn").prop('disabled', true);
                        $('#valid').html(response.message).show();
                        return true;
                    }
                });
            });
        });
    </script>
</div>

