<?php
$_order = $block->getOrder();
$transactionId = $block->getTransactionId($_order->getId());
$paymentMode = $block->getPaymentMode($_order->getId());
?>
<?php if ($transactionId): ?>
    <div class="admin__field">
        <div>
            <strong class="admin__field-label"><?= $block->escapeHtml(__('Transaction ID')) ?>:&nbsp;&nbsp;&nbsp;</strong>
            <span class="admin__field-value"><?= $block->escapeHtml($transactionId) ?></span>
        </div>
        <div>
            <strong class="admin__field-label"><?= $block->escapeHtml(__('Mode Of Payment')) ?>:</strong>
            <div class="admin__field-value">
                <?php echo $paymentMode."\n"; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
