<?php
$_order = $block->getOrder();
$transactionId = $block->getTransactionId($_order->getId());
$paymentMode = $block->getPaymentMode($_order->getId());
?>
<?php if ($transactionId): ?>
    <div class="admin__field">
        <div>
            <strong class="admin__field-label">
                <?= $escaper->escapeHtml(__('Transaction ID')) ?>:&nbsp
            </strong>
            <span class="admin__field-value"><?= $escaper->escapeHtml($transactionId) ?></span>
        </div>
        <div>
            <strong class="admin__field-label"><?= $escaper->escapeHtml(__('Mode Of Payment')) ?>:</strong>
            <div class="admin__field-value">
                <?= $escaper->escapeHtml($paymentMode)."\n"; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
